import time
import requests

GITHUB_API = "https://api.github.com"
BOT_FOOTER = "\n\n---\n*🤖 Generated by code-review-bot*"


def _headers(token: str) -> dict:
    return {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }


def _request_with_backoff(method: str, url: str, token: str, **kwargs) -> requests.Response:
    """
    Wraps every GitHub API call with exponential backoff.
    
    Why? GitHub returns 403 or 429 when you hit rate limits.
    Instead of crashing, we wait and retry up to 3 times.
    Doubling the wait each time (1s → 2s → 4s) is the standard
    pattern — it gives the API time to recover without hammering it.
    """
    wait = 1
    for attempt in range(3):
        resp = requests.request(
            method, url,
            headers=_headers(token),
            **kwargs
        )

        if resp.status_code == 429 or resp.status_code == 403:
            # Check if GitHub told us exactly how long to wait
            retry_after = resp.headers.get("Retry-After")
            wait_time = int(retry_after) if retry_after else wait
            print(f"   ⚠️ Rate limited. Waiting {wait_time}s before retry {attempt + 1}/3")
            time.sleep(wait_time)
            wait *= 2  # exponential backoff
            continue

        return resp

    # All retries exhausted
    resp.raise_for_status()
    return resp


def find_existing_bot_comment(repo: str, pr_number: int, token: str) -> int | None:
    """
    Looks for an existing comment from this bot on the PR.
    Returns the comment ID if found, None if not.
    
    Why search by footer text? GitHub Apps don't have a simple
    "is this mine?" flag on comments. The footer string is our
    reliable way to identify bot-generated comments.
    """
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    resp = _request_with_backoff("GET", url, token)

    if resp.status_code != 200:
        return None

    for comment in resp.json():
        if BOT_FOOTER.strip() in comment["body"]:
            return comment["id"]

    return None


def format_review_comment(review: dict) -> str:
    """
    Turns the structured review dict into markdown.
    GitHub renders markdown in comments — bullets, headers, code blocks all work.
    """
    risks = review.get("risks", [])
    suggestions = review.get("suggestions", [])
    test_note = review.get("test_coverage", "")
    summary = review.get("summary", "")

    # Format risks as bullet list
    risks_md = "\n".join(f"- {r}" for r in risks) if risks else "_None detected_"

    # Format suggestions as bullet list
    suggestions_md = "\n".join(f"- {s}" for s in suggestions) if suggestions else "_None_"

    return f"""## 🔍 Code Review

**Summary:** {summary}

### ⚠️ Risks
{risks_md}

### 💡 Suggestions
{suggestions_md}

### 🧪 Test Coverage
{test_note}
{BOT_FOOTER}"""


def post_or_update_comment(
    repo: str,
    pr_number: int,
    review: dict,
    token: str
) -> str:
    """
    Main entry point for Phase 4.
    
    Checks if a bot comment already exists:
    - If yes: PATCH (edit) that comment — keeps the PR clean
    - If no: POST a new comment
    
    Returns "created" or "updated" for logging.
    """
    body = format_review_comment(review)
    existing_id = find_existing_bot_comment(repo, pr_number, token)

    if existing_id:
        # Edit the existing comment
        url = f"{GITHUB_API}/repos/{repo}/issues/comments/{existing_id}"
        resp = _request_with_backoff("PATCH", url, token, json={"body": body})
        resp.raise_for_status()
        print(f"   ✏️ Updated existing bot comment #{existing_id}")
        return "updated"
    else:
        # Create a new comment
        url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
        resp = _request_with_backoff("POST", url, token, json={"body": body})
        resp.raise_for_status()
        comment_id = resp.json()["id"]
        print(f"   💬 Posted new bot comment #{comment_id}")
        return "created"